#!/usr/bin/env python
#<<<rconcheck>>>
#[b'hostname: W2TJ Competitive Server
#version : 1.37.5.3/13753 1119/7863 insecure  [INVALID_STEAMID]
#udp/ip  : 10.0.7.13:27015
#os      :  Linux
#type    :  community dedicated
#map     : de_dust2
#players : 0 humans, 0 bots (30/0 max) (hibernating)
