#!/usr/bin/env python3
from srcds.rcon import RconConnection
import socket
hostname = socket.gethostname()
ip = socket.gethostbyname(hostname)
print ("<<<rconcheck>>>")
try:
    conn = RconConnection(ip, port=27015, password='passwort')
    response = conn.exec_command('status')
    print (response.replace("\\n","\n"))
except:
    print("Something went wrong")
